apiVersion: mongodb.storage.dolittle.io/v1
kind: Cluster
metadata:
  name: example-cluster
spec:
  replicas: 2
  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: "8Gi"
    storageClassName: "managed-premium"
