apiVersion: apps/v1
kind: Deployment
metadata:
  name: Storage.MongoDB
spec:
  replicas: 1
  selector:
    matchLabels:
      name: Storage.MongoDB
  template:
    metadata:
      labels:
        name: Storage.MongoDB
    spec:
      serviceAccountName: Storage.MongoDB
      containers:
        - name: Storage.MongoDB
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - Storage.MongoDB
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "Storage.MongoDB"
