kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: Storage.MongoDB
subjects:
- kind: ServiceAccount
  name: Storage.MongoDB
roleRef:
  kind: Role
  name: Storage.MongoDB
  apiGroup: rbac.authorization.k8s.io
